In [6]:
import numpy as np
n = 10
x = np.random.normal(size=n)
print(x)

[-0.6347799  -0.49068936  0.04796807  0.19322496 -0.53974029  0.47161163
  0.06935304  0.28002172 -0.57903304  2.26141416]


In [7]:
import numpy as np
x = np.array([1,2,3])
print(x)

[1 2 3]


In [12]:
import numpy as np
x = np.log(np.array([4,7,8]))
print(x)

[1.38629436 1.94591015 2.07944154]


In [15]:
import numpy as np
from math import log
x = np.array([4,7,8])

for i in range(0, len(x)):
    x[i]=log(x[i])
print(x)



[1 1 2]
